In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df_People = pd.read_csv('Raw CSV\People.csv', encoding="ISO-8859-1")
df_AllStarFull = pd.read_csv('Raw CSV\AllstarFull.csv', encoding="ISO-8859-1")
df_Batting = pd.read_csv('Raw CSV\Batting.csv', encoding="ISO-8859-1")
df_Fielding = pd.read_csv('Raw CSV\Fielding.csv', encoding="ISO-8859-1")
df_Pitching = pd.read_csv('Raw CSV\Pitching.csv', encoding="ISO-8859-1")
df_HOF = pd.read_csv('Raw CSV\HallOfFame.csv', encoding= "ISO-8859-1")
df_Appearances = pd.read_csv('Raw CSV\Appearances.csv',encoding ="ISO-8859-1")

FileNotFoundError: [Errno 2] No such file or directory: 'Raw CSV\\People.csv'

In [ ]:
df_Pitching.shape

(49430, 30)

In [ ]:
df_Pitching.head()

,playerID,yearID,stint,teamID,lgID,W,L,G,GS,CG,...,IBB,WP,HBP,BK,BFP,GF,R,SH,SF,GIDP
0,bechtge01,1871,1,PH1,NaN,1,2,3,3,2,...,NaN,7,NaN,0,146.0,0,42,NaN,NaN,NaN
1,brainas01,1871,1,WS3,NaN,12,15,30,30,30,...,NaN,7,NaN,0,1291.0,0,292,NaN,NaN,NaN
2,fergubo01,1871,1,NY2,NaN,0,0,1,0,0,...,NaN,2,NaN,0,14.0,0,9,NaN,NaN,NaN
3,fishech01,1871,1,RC1,NaN,4,16,24,24,22,...,NaN,20,NaN,0,1080.0,1,257,NaN,NaN,NaN
4,fleetfr01,1871,1,NY2,NaN,0,1,1,1,1,...,NaN,0,NaN,0,57.0,0,21,NaN,NaN,NaN

In [ ]:
df_Pitching.columns

Index(['playerID', 'yearID', 'stint', 'teamID', 'lgID', 'W', 'L', 'G', 'GS',
       'CG', 'SHO', 'SV', 'IPouts', 'H', 'ER', 'HR', 'BB', 'SO', 'BAOpp',
       'ERA', 'IBB', 'WP', 'HBP', 'BK', 'BFP', 'GF', 'R', 'SH', 'SF', 'GIDP'],
      dtype='object')

In [ ]:
nulls = df_Pitching.isnull().sum()
nulls[nulls > 0]

lgID       132
BAOpp     4441
ERA         97
IBB      14578
HBP        734
BFP          3
SH       19187
SF       19187
GIDP     20318
dtype: int64

In [ ]:
df_Pitching.fillna(0, inplace=True)

In [ ]:
#Need to also drop Percentages (ERA) - Will Calculate Later If Necessary
df_Pitching.drop(columns=['yearID',
                          'teamID',
                          'lgID',
                          'IBB',
                          'WP',
                          'BK',
                          'SH',
                          'SF',
                          'GIDP',
                          'BAOpp',
                          'HBP',
                          'ERA'], 
                    axis=1, inplace=True)

In [ ]:
#Stint will give the same result... Change Stint to Seasons, drop year ID

#df_Season_Pitching = df_Pitching.groupby(['playerID'])['yearID'].unique().reset_index()
#df_Season_Pitching['seasons'] = df_Season_Pitching['yearID'].apply(lambda x: len(x))
#df_Season_Pitching.drop(['yearID'], axis=1, inplace = True)
#df_Season_Pitching

In [ ]:
df_Pitching_Grouped = df_Pitching.groupby(['playerID']).sum()

In [ ]:
df_Pitching_Grouped

,stint,W,L,G,GS,CG,SHO,SV,IPouts,H,ER,HR,BB,SO,BFP,GF,R
playerID,,,,,,,,,,,,,,,,,
aardsda01,9,16,18,331,0,0,0,69,1011,296,160,41,183,340,1475.0,141,169
aasedo01,13,66,60,448,91,22,5,82,3328,1085,468,89,457,641,4730.0,235,503
abadfe01,12,8,29,400,6,0,0,2,1045,332,146,43,123,290,1481.0,101,155
abbeybe01,7,22,40,79,65,52,0,1,1704,686,285,18,192,161,2568.0,14,442
abbeych01,1,0,0,1,0,0,0,0,6,6,1,0,0,0,12.0,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zuberbi01,13,43,42,224,65,23,3,6,2358,767,374,35,468,383,3476.0,90,418
zuberty01,2,1,5,54,0,0,0,0,148,41,29,10,37,55,222.0,14,31
zumayjo01,5,13,12,171,0,0,0,5,629,169,71,18,114,210,911.0,35,80
zuverge01,12,32,36,265,31,9,2,40,1927,660,253,56,203,223,2746.0,139,296
zychto01,3,7,3,70,1,0,0,1,218,57,22,3,34,80,309.0,14,24

In [ ]:
## Since Stint Appears to be the Same as Seasons, Change Name
df_Pitching_Grouped.rename(columns={'stint':'Seasons'}, inplace=True)

In [ ]:
df_Pitching_Grouped

,Seasons,W,L,G,GS,CG,SHO,SV,IPouts,H,ER,HR,BB,SO,BFP,GF,R
playerID,,,,,,,,,,,,,,,,,
aardsda01,9,16,18,331,0,0,0,69,1011,296,160,41,183,340,1475.0,141,169
aasedo01,13,66,60,448,91,22,5,82,3328,1085,468,89,457,641,4730.0,235,503
abadfe01,12,8,29,400,6,0,0,2,1045,332,146,43,123,290,1481.0,101,155
abbeybe01,7,22,40,79,65,52,0,1,1704,686,285,18,192,161,2568.0,14,442
abbeych01,1,0,0,1,0,0,0,0,6,6,1,0,0,0,12.0,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zuberbi01,13,43,42,224,65,23,3,6,2358,767,374,35,468,383,3476.0,90,418
zuberty01,2,1,5,54,0,0,0,0,148,41,29,10,37,55,222.0,14,31
zumayjo01,5,13,12,171,0,0,0,5,629,169,71,18,114,210,911.0,35,80
zuverge01,12,32,36,265,31,9,2,40,1927,660,253,56,203,223,2746.0,139,296
zychto01,3,7,3,70,1,0,0,1,218,57,22,3,34,80,309.0,14,24

In [ ]:
df_Pitching_Grouped.columns

Index(['Seasons', 'W', 'L', 'G', 'GS', 'CG', 'SHO', 'SV', 'IPouts', 'H', 'ER',
       'HR', 'BB', 'SO', 'BFP', 'GF', 'R'],
      dtype='object')

In [ ]:
df_Pitching_Grouped.rename(columns={'W':'Wins', 
                                    'L':'Losses', 
                                    'G':'Games', 
                                    'GS':'Games_Started', 
                                    'CG':'Complete_Games', 
                                    'SHO':'Shutouts', 
                                    'SV':'Saves', 
                                    'IPouts':'Outs_Pitched', 
                                    'H':'Hits', 
                                    'ER':'Earned_Runs',
                                    'HR':'Home_Runs', 
                                    'BB':'Walks', 
                                    'SO':'Strikeouts',  
                                    'BFP':'Batters_Faced', 
                                    'GF':'Games_Finished', 
                                    'R':'Runs_Allowed'
                                    })

,Seasons,Wins,Losses,Games,Games_Started,Complete_Games,Shutouts,Saves,Outs_Pitched,Hits,Earned_Runs,Home_Runs,Walks,Strikeouts,Batters_Faced,Games_Finished,Runs_Allowed
playerID,,,,,,,,,,,,,,,,,
aardsda01,9,16,18,331,0,0,0,69,1011,296,160,41,183,340,1475.0,141,169
aasedo01,13,66,60,448,91,22,5,82,3328,1085,468,89,457,641,4730.0,235,503
abadfe01,12,8,29,400,6,0,0,2,1045,332,146,43,123,290,1481.0,101,155
abbeybe01,7,22,40,79,65,52,0,1,1704,686,285,18,192,161,2568.0,14,442
abbeych01,1,0,0,1,0,0,0,0,6,6,1,0,0,0,12.0,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zuberbi01,13,43,42,224,65,23,3,6,2358,767,374,35,468,383,3476.0,90,418
zuberty01,2,1,5,54,0,0,0,0,148,41,29,10,37,55,222.0,14,31
zumayjo01,5,13,12,171,0,0,0,5,629,169,71,18,114,210,911.0,35,80
zuverge01,12,32,36,265,31,9,2,40,1927,660,253,56,203,223,2746.0,139,296
zychto01,3,7,3,70,1,0,0,1,218,57,22,3,34,80,309.0,14,24

In [ ]:
df_Pitching_Grouped.to_csv('Clean CSV\Clean_Pitching.csv', index=False)